baseURL = 'https://helenaeliasmusic.ch/'
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = false
title = 'Helena Elias Music'
enableRobotsTXT = true

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[params]
  author = "Helena Elias Music"
  description = "Helena & Elias - Dein Duo für jeden Anlass"

[markup.goldmark.renderer]
  unsafe = true

[languages.de]
  languageName = "DE"
  languageCode = "de"
  weight = 1
  title = "Helena Elias Music"

[languages.en]
  languageName = "EN"
  languageCode = "en"
  weight = 2
  title = "Helena Elias Music"
